### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by artisanchurch** [artisanchurch/prototype#5]
- Mailing address
- Emails
  - info
  - prayer
  - giving
  - care? (clarify what emails get sent here)
- People
  - Scott
  - Jessie
  - LT chair _(confirm it's okay to publish name/email)_
  - PRC chair _(confirm it's okay to publish name/email)_
- Social media
  - Twitter
  - Facebook
- Contact form
  - Generic for now

**Comment by artisanchurch** [comment]
Mostly done. Just waiting on confirmation from Care Project coordinator and LT chair.

**Comment by jrsconfitto** [comment]
I'm onboard. James at artisan address please!

**Comment by artisanchurch** [comment]
:+1:

**Comment by sj-austin** [comment]
Please add Instagram to the social media page.
